---
language: python
python:
  - "3.6"
services:
  - docker
env:
  - INSTALL_MODE=github_releases DISTRIB=centos7
  - INSTALL_MODE=github_releases DISTRIB=centos6
  - INSTALL_MODE=github_releases DISTRIB=fedora31
  - INSTALL_MODE=github_releases DISTRIB=fedora30
  - INSTALL_MODE=github_releases DISTRIB=fedora29
  - INSTALL_MODE=github_releases DISTRIB=ubuntu1804
  - INSTALL_MODE=package_manager DISTRIB=ubuntu1804
  - INSTALL_MODE=github_releases DISTRIB=ubuntu1604
  - INSTALL_MODE=github_releases DISTRIB=debian10
  - INSTALL_MODE=package_manager DISTRIB=debian10
  - INSTALL_MODE=github_releases DISTRIB=debian9
  - INSTALL_MODE=github_releases DISTRIB=debian8
script:
  - molecule --version
  - molecule test
# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
