---
language: python
services:
  - docker

env:
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: fedora31
    - MOLECULE_DISTRO: fedora30
    - MOLECULE_DISTRO: fedora29
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian8

script:
  - molecule test

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
