---
# Note: we don't use the GitHub API to retrieve the latest version because
# it has rate limits which are hard to avoid in CI (we need a token, authenticate
# with the API, etc.). Instead, we browse the latest release url which redirects
# to the release page, where we can find the version number in the URL.
- become: no
  delegate_to: localhost
  run_once: yes
  block:
  - name: Get latest release information from GitHub
    uri:
      url: "{{ mergerfs_github_releases_url }}/latest"
    register: mergerfs_github_release_page
  - name: Set latest mergerfs version fact
    set_fact:
      mergerfs_version: "{{ mergerfs_github_release_page['url'].split('/')[-1] }}"
  when: mergerfs_version == "latest"

- name: Determine package download url
  set_fact:
    pkg_url: "{{ mergerfs_github_releases_url }}/download/{{ mergerfs_version }}/{{ mergerfs_pkg_prefix }}{{ mergerfs_version }}{{ mergerfs_pkg_suffix }}"

- name: Install xz-utils package for .deb package installation
  become: yes
  apt:
    name: xz-utils
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Install mergerfs package with apt
  become: yes
  apt:
    deb: "{{ pkg_url }}"
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Install mergerfs package with yum
  become: yes
  yum:
    name: "{{ pkg_url }}"
    state: present
  when: ansible_pkg_mgr == 'yum'

- name: Install mergerfs package with dnf
  become: yes
  dnf:
    name: "{{ pkg_url }}"
    state: present
  when: ansible_pkg_mgr == 'dnf'
