---

- name: Install mergerfs prerequisites
  ansible.builtin.dnf:
    name: "{{ mergerfs_prerequisites }}"
    state: present
  become: true
  when: mergerfs_install_prerequisites

- name: Install mergerfs package
  ansible.builtin.dnf:
    name: "{{ mergerfs_package_url }}"
    state: present
    disable_gpg_check: true  # the package is not signed
  become: true
