---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install mergerfs package via apt
  become: yes
  apt:
    deb: "{{ package_url }}"
    state: present
  when: ansible_pkg_mgr == 'apt'
