---

- name: Include OS-specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"
  tags: mergerfs

- name: Install mergerfs prerequisites
  become: true
  ansible.builtin.package:
    name: "{{ mergerfs_prerequisites }}"
    state: present
  tags: [mergerfs, mergerfs_install]

- name: Include install tasks
  ansible.builtin.include_tasks:
    file: install_from_{{ mergerfs_install_mode }}.yml
  tags: [mergerfs, mergerfs_install]

- name: Mount mergerfs filesystems
  ansible.posix.mount:
    fstype: fuse.mergerfs
    src: "{{ ':'.join(item.branches | mandatory) }}"
    path: "{{ item.path | mandatory }}"
    opts: "{{ item.options | default('defaults') }}"
    state: "{{ item.state | default('mounted') }}"  # noqa args[module]
  loop: "{{ mergerfs_mounts }}"
  become: true
  tags: [mergerfs, mergerfs_install]
