---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# TODO: determine latest version
# - name: Determine latest version
#   github_release:
#     user: trapexit
#     repo: mergerfs
#     action: latest_release

- name: Install mergerfs package with apt
  become: yes
  apt:
    deb: "{{ package_url }}"
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Install mergerfs package with yum
  become: yes
  yum:
    name: "{{ package_url }}"
    state: present
  when: ansible_pkg_mgr == 'yum'

- name: Install mergerfs package with dnf
  become: yes
  dnf:
    name: "{{ package_url }}"
    state: present
  when: ansible_pkg_mgr == 'dnf'

- name: Mount mergerfs filesystems
  become: yes
  mount:
    fstype: fuse.mergerfs
    src: "{{ ':'.join(item.branches | mandatory) }}"
    path: "{{ item.path | mandatory }}"
    opts: "{{ item.options | default('defaults') }}"
    state: "{{ item.state | default('mounted') }}"
  loop: "{{ mergerfs_mounts }}"
