---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - mergerfs

- name: Update apt cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_pkg_mgr == 'apt'
  tags:
    - mergerfs
    - mergerfs_install

- name: Install mergerfs prerequisites
  become: true
  package:
    name: "{{ mergerfs_prerequisites }}"
    state: present
  tags:
    - mergerfs
    - mergerfs_install

- name: Include install tasks
  import_tasks: install_from_{{ mergerfs_install_mode }}.yml
  tags:
    - mergerfs
    - mergerfs_install

- name: Mount mergerfs filesystems
  become: true
  mount:
    fstype: fuse.mergerfs
    src: "{{ ':'.join(item.branches | mandatory) }}"
    path: "{{ item.path | mandatory }}"
    opts: "{{ item.options | default('defaults') }}"
    state: "{{ item.state | default('mounted') }}"
  loop: "{{ mergerfs_mounts }}"
  tags:
    - mergerfs
    - mergerfs_mount
