---
- block:
    - name: Get latest release information from GitHub
      uri:
        url: "https://api.github.com/repos/trapexit/mergerfs/releases/latest"
      register: mergerfs_latest_release
    - name: Extract its version number
      set_fact:
        mergerfs_version: "{{ mergerfs_latest_release.json['tag_name'] }}"
  delegate_to: localhost
  become: False
  run_once: True
  when: mergerfs_version == "latest"

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Determine package download url
  set_fact:
    pkg_url: "https://github.com/trapexit/mergerfs/releases/download/{{ mergerfs_version }}/{{ pkg_filename }}"

- name: Install mergerfs package with apt
  become: True
  apt:
    deb: "{{ pkg_url }}"
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Install mergerfs package with yum
  become: True
  yum:
    name: "{{ pkg_url }}"
    state: present
  when: ansible_pkg_mgr == 'yum'

- name: Install mergerfs package with dnf
  become: True
  dnf:
    name: "{{ pkg_url }}"
    state: present
  when: ansible_pkg_mgr == 'dnf'

- name: Mount mergerfs filesystems
  become: True
  mount:
    fstype: fuse.mergerfs
    src: "{{ ':'.join(item.branches | mandatory) }}"
    path: "{{ item.path | mandatory }}"
    opts: "{{ item.options | default('defaults') }}"
    state: "{{ item.state | default('mounted') }}"
  loop: "{{ mergerfs_mounts }}"
