---
- name: Install mergerfs dependencies
  become: True
  package:
    name: fuse
    state: present

- name: Include install tasks
  include_tasks: install_from_github_releases.yml

- name: Mount mergerfs filesystems
  become: True
  mount:
    fstype: fuse.mergerfs
    src: "{{ ':'.join(item.branches | mandatory) }}"
    path: "{{ item.path | mandatory }}"
    opts: "{{ item.options | default('defaults') }}"
    state: "{{ item.state | default('mounted') }}"
  loop: "{{ mergerfs_mounts }}"
