---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "$MOLECULE_PROJECT_DIRECTORY/.."
  inventory:
    group_vars:
      all:
        ansible_user: root
        mergerfs_install_tools: true
        mergerfs_mounts:
          - path: /mnt/storage
            branches:
              - /mnt/data*
            options: allow_other,use_ino

verifier:
  name: testinfra
  env:
    PYTEST_CHECK_TEST_ID_REGEX: "0"
