---
name: CI
on:  # yamllint disable-line rule:truthy
  push:
    tags-ignore:
      - '**'
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2004
          - debian12
          - debian11
          - rockylinux8
          - rockylinux9
          - fedora39

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run molecule tests
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: molecule -v test
